"""empty message

Revision ID: 1e6436d12edc
Revises: fdc720c8a58a
Create Date: 2022-06-03 15:22:03.980924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e6436d12edc'
down_revision = 'fdc720c8a58a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('created_on', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artist', 'created_on')
    # ### end Alembic commands ###
