"""empty message

Revision ID: e24e9dbe0775
Revises: 1e38dad977c4
Create Date: 2022-06-02 19:18:46.374035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e24e9dbe0775'
down_revision = '1e38dad977c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('created_on', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venue', 'created_on')
    # ### end Alembic commands ###
