"""empty message

Revision ID: f6ba12d4ec92
Revises: 0983f148c059
Create Date: 2022-06-04 05:29:29.175965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6ba12d4ec92'
down_revision = '0983f148c059'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('song')
    op.drop_table('album')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('album',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('album_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('artist_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artist.id'], name='album_artist_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='album_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('song',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('album_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['album_id'], ['album.id'], name='song_album_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='song_pkey')
    )
    # ### end Alembic commands ###
